config/routes.rb
Farmersmarketapp::Application.routes.draw do

  resources :vendors
  resource :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  root 'vendors#index'

end

app/models/user.rb
require "bcrypt"
class User
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  validates_presence_of :name, :email, :password_digest, message: "One or more of the fields was not completed, please update."

  belongs_to :vendor

  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
    if BCrypt::Password.new(self.password_digest) == test_password
      self
    else
      false
    end
  end
end

app/models/vendor.rb
class Vendor
  include Mongoid::Document
  field :name, type: String
  field :stall, type: Integer
  field :owner, type: String
  field :location, type: String
  field :type, type: String
  field :site, type: String
  field :comments, type: String

  validates_presence_of :name, :stall, :owner, :location, :type, :site, :comments, message: "One or more of the fields were not filled out."

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
#authenticates user and redirects sign in
  def authenticate_user
    if !self.current_user
      redirect_to new_sessions_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

#login that finds user based on email
  def create
    @user = User.where(:email => params[:session][:email]).first
    if @user == nil || !@user.authenticate(params[:session][:password])
      render 'new'
    else
      session[:remember_token] = @user.id
      @current_user = @user
      redirect_to vendors_path
    end
  end

#logout
  def destroy
    session.delete(:remember_token)
    redirect_to vendors_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have successfully signed up!"
      session[:remember_token] = @user.id
      @current_user = @user
      redirect_to vendors_path
    else
      render :new
    end
  end

protected
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  before_action :authenticate_user, only: [:new, :create, :update, :edit, :destroy]
  before_action :set_user, only: [:new, :create]

  def index
    @vendors = Vendor.all
  end

  def show
    @vendor = Vendor.find(params[:id])
  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.new(params.require(:vendor).permit(:name, :stall, :owner, :location, :type, :site, :comments))
    @vendor.owner = @current_user.name
    if @vendor.save
      flash[:success] = "Your entry has been created!"
      redirect_to vendors_path
    else
      render 'new'
    end
  end

  def edit
    @vendor = Vendor.find(params[:id])
  end

  def update
    @vendor = Vendor.find(params[:id])
      if @vendor.update_attributes(params.require(:vendor).permit(:name, :stall, :owner, :location, :type, :site, :comments))
        flash[:success] = "Your entry has been updated!"
        redirect_to vendors_path
      else
        render 'edit'
    end
  end

  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy
    Vendor.where(vendor_id: @vendor.id).destroy
    redirect_to vendors_path
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:remember_token]
      @current_user ||= User.find(session[:remember_token])
    else
      @current_user = nil
    end
  end
end

app/helpers/sessionscontroller_helper.rb
module SessionscontrollerHelper
end

app/helpers/userscontroller_helper.rb
module UserscontrollerHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Farmersmarketapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Cabin+Sketch' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Quicksand:700' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

</head>
<body>
  <nav class="navbar navbar-inverse transparent navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home Page', vendors_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if !current_user %>
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li><%= link_to "Sign In", new_sessions_path %></li>
          <% else %>
            <li><%= link_to "Add a Vendor", new_vendor_path %></li>
            <li><%= link_to "Logout", sessions_path, :method => :delete %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<div class="container-fluid">
  <%flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <ul class="list-group">
    <% @user.errors.messages.each do |message| %>
      <li class="list-group-item list-group-item-danger"><%= message[1][0].to_s %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <h1 class="text-center">Sign Up</h1>
  <br>
  <div class="text-center">
    <%= form_for @user do |f| %>
      Name <span><%= f.text_field :name %></span>
      Email <span><%= f.text_field :email %></span>
      Password <span><%= f.password_field :password %></span>
    <br>
    <br>
    <span><%= f.submit %></span>
    <% end %>
  </div>
</div>

app/views/vendors/_form.html.erb
<div class= "possibleerrors">
  <%#Show errors%>
<% if @vendor.errors.any? %>
  <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being added:</h2>
  <ul class="list-group">
    <% @vendor.errors.messages.each do |message| %>
      <li class="list-group-item list-group-item-danger"><%= message[1][0].to_s %></li>
    <% end %>
  </ul>
<% end %>

<%=  form_for(@vendor) do |f| %>
  <div class="container">
    <div class="field"><strong>Name</strong><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <br>
    <div class="field"><strong>Stall</strong><br>
      <%= f.text_field :stall, class: "form-control" %>
    </div>
    <br>
    <div class="field"><strong>Owner</strong><br>
      <%= f.text_field :owner, value: current_user.name, class: "form-control" %>
    </div>
    <br>
    <div class="field"><strong>Location</strong><br>
      <%= f.text_field :location, class: "form-control" %>
    </div>
    <br>
    <div class="field"><strong>Specialty</strong><br>
      <%= f.text_field :type, class: "form-control" %>
    </div>
    <br>
    <div class="field"><strong>Website</strong><br>
      <%= f.text_field :site, class: "form-control" %>
    </div>
    <br>
    <div class="field"><strong>Comments</strong><br>
      <!-- text_area allows for moving text entry adn thr 50x10 sets a min size for box -->
      <%= f.text_area :comments, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<div class="container">
  <h1 class="text-center">Vendors Edit</h1>
    <%= render 'form' %>
</div>

app/views/vendors/index.html.erb
<div class="container">
  <h1 class="text-center"> Encino Farmer's Market Vendors</h1><br>
    <p class="text-center">Come visit the Encino Farmer's Market on Sundays between 8am and 2pm<br>Click on the vendor's name to view additional details.</p><br>

    <% @vendors.each do |v| %>
      <div class="jobshover">
        <%= link_to(vendor_path(v)) do %><div class="attributes"><strong>Name: &nbsp;</strong><%= v.name %></div>
        <% end %>
        <div class="attributes"><strong>Specialty: &nbsp;</strong> <%= v.type %></div>
        <div class="attributes"><strong>Comments: &nbsp;</strong> <%= v.comments %></div>

        <% if (current_user && v.owner == current_user.name) %>
          <%= link_to "Edit", edit_vendor_path(v) %>
          <%= link_to "Delete", v, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        <br>
        <br>
        </div>
        <% end %>
</div>

app/views/vendors/new.html.erb
<div class="container">
  <h1 class="text-center">Create a New Vendor</h1>
    <p class="text-center">Please fill in the below information</p>
      <%= render 'form' %>
</div>

app/views/vendors/show.html.erb
<div class="container">
  <h1 class="text-center"> <%= @vendor.name %> </h1>
    <div class="attributes"><strong>Name:</strong> <%= @vendor.name %> </div><br>
    <div class="attributes"><strong>Stall:</strong> <%= @vendor.stall %> </div><br>
    <div class="attributes"><strong>Owner:</strong> <%= @vendor.owner %> </div><br>
    <div class="attributes"><strong>Location:</strong> <%= @vendor.location %> </div><br>
    <div class="attributes"><strong>Specialty:</strong> <%= @vendor.type %> </div><br>
    <div class="attributes"><strong>Website:</strong> <a href="<%= @vendor.site %>"><%= @vendor.site %></a></div><br>
    <div class="attributes"><strong>Comments:</strong> <%= @vendor.comments %> </div>
    <br>
</div>